image: alpine:latest

before_script:
  - apk update
  - 'which rsync || (apk add rsync)'
  - 'which ssh-agent || (apk add openssh-client)'
  - mkdir -p ~/.ssh
  - chmod 0700 ~/.ssh
  - eval $(ssh-agent -s)
  - "[[ -f /.dockerenv ]] && cat $SSH_CONFIG > ~/.ssh/config"

deploy_prod:
  stage: deploy
  script:
    - chmod 600 $STAGING_PRIVATE_KEY
    - ssh-add $STAGING_PRIVATE_KEY
    - chmod -R 755 src/
    - rsync -azP src/ $REMOTE_HOST:/srv/www/joeecob.uk/
  environment:
    name: production
    url: https://joeecob.uk
  only:
    - master
